"""Initial migration

Revision ID: c57518f3b72e
Revises: 
Create Date: 2026-08-21 23:02:41.426104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c57518f3b72e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('data_emissao', sa.Date(), nullable=True),
    sa.Column('tipo', sa.String(length=50), server_default='Reunião', nullable=False),
    sa.Column('situacao', sa.String(length=20), server_default='Rascunho', nullable=False),
    sa.Column('local', sa.String(length=255), nullable=True),
    sa.Column('presidente', sa.String(length=255), nullable=True),
    sa.Column('secretario', sa.String(length=255), nullable=True),
    sa.Column('participantes', sa.Text(), nullable=True),
    sa.Column('pauta', sa.Text(), nullable=True),
    sa.Column('deliberacoes', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certificados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('data_emissao', sa.Date(), nullable=True),
    sa.Column('criado_por', sa.String(length=200), nullable=True),
    sa.Column('evento', sa.String(length=200), nullable=True),
    sa.Column('corpo', sa.Text(), nullable=True),
    sa.Column('situacao', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_fim', sa.DateTime(), nullable=False),
    sa.Column('local', sa.String(length=150), nullable=True),
    sa.Column('organizador', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('public_token', sa.String(length=16), nullable=False),
    sa.Column('token_expira_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_token')
    )
    op.create_table('igreja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.String(length=200), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('site', sa.String(length=120), nullable=True),
    sa.Column('pastor_responsavel', sa.String(length=120), nullable=True),
    sa.Column('ano_fundacao', sa.Integer(), nullable=True),
    sa.Column('versiculo_tema', sa.String(length=250), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=100), nullable=False),
    sa.Column('tarefa', sa.String(length=255), nullable=False),
    sa.Column('resultado', sa.String(length=50), nullable=False),
    sa.Column('datahora', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('foto', sa.String(length=200), nullable=True),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('sexo', sa.String(length=20), nullable=True),
    sa.Column('estado_civil', sa.String(length=20), nullable=True),
    sa.Column('conjuge', sa.String(length=120), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('endereco', sa.String(length=200), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cep', sa.String(length=20), nullable=True),
    sa.Column('batizado', sa.Boolean(), nullable=True),
    sa.Column('dizimista', sa.Boolean(), nullable=True),
    sa.Column('data_batismo', sa.Date(), nullable=True),
    sa.Column('funcao', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('data_cadastro', sa.Date(), nullable=True),
    sa.Column('numero_carteira', sa.String(length=50), nullable=True),
    sa.Column('igreja_local', sa.String(length=120), nullable=True),
    sa.Column('validade', sa.Date(), nullable=True),
    sa.Column('data_conversao', sa.Date(), nullable=True),
    sa.Column('data_saida', sa.Date(), nullable=True),
    sa.Column('visitante', sa.Boolean(), nullable=True),
    sa.Column('nacionalidade', sa.String(length=50), nullable=True),
    sa.Column('naturalidade', sa.String(length=50), nullable=True),
    sa.Column('rg', sa.String(length=20), nullable=True),
    sa.Column('cpf', sa.String(length=20), nullable=True),
    sa.Column('pai', sa.String(length=120), nullable=True),
    sa.Column('mae', sa.String(length=120), nullable=True),
    sa.Column('filiacao', sa.String(length=200), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patrimonios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('numero', sa.String(length=50), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('data_entrada', sa.Date(), nullable=True),
    sa.Column('situacao', sa.String(length=50), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('public_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cartas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('data_emissao', sa.Date(), nullable=True),
    sa.Column('remetente', sa.String(length=200), nullable=True),
    sa.Column('destinatario', sa.String(length=200), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('corpo', sa.Text(), nullable=True),
    sa.Column('situacao', sa.String(length=20), nullable=False),
    sa.Column('membro_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['membro_id'], ['members.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financeiro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('conta', sa.String(length=100), nullable=False),
    sa.Column('departamento', sa.String(length=100), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('membro_id', sa.Integer(), nullable=True),
    sa.Column('cpf_membro', sa.String(length=14), nullable=True),
    sa.Column('cnpj_fornecedor', sa.String(length=18), nullable=True),
    sa.Column('conciliado', sa.Boolean(), nullable=True),
    sa.Column('comprovante', sa.String(length=200), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usuario', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['membro_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_permissions')
    op.drop_table('financeiro')
    op.drop_table('cartas')
    op.drop_table('users')
    op.drop_table('public_links')
    op.drop_table('permissions')
    op.drop_table('patrimonios')
    op.drop_table('members')
    op.drop_table('logs')
    op.drop_table('igreja')
    op.drop_table('eventos')
    op.drop_table('certificados')
    op.drop_table('atas')
    # ### end Alembic commands ###
